### ISSUE TITLE
Vector2D Interpolation

### ISSUE THREAD

**Issue by Kython89** [FRCTeam2910/Common-Public#1]
In Vector2D interpolate the `<` and `>` are swapped.  In most common cases where 0 <=  t <= 1.0 it will return `this`.
```
public Vector2 interpolate(Vector2 other, double t) {
		if (t >= 0.0) {
			return this;
		} else if (t <= 1.0) {
			return other;
		} else {
			return extrapolate(other, t);
		}
	}
```

**Comment by JacobJBublitz** [comment]
Thanks for letting me know about this! I guess this is what happens when I write code but never write tests for it
